-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgSseDzUvVxLvGgPCS
peX4n6+pdCn92Syvq5dn5u8/2mugCgYIKoZIzj0DAQehRANCAASTNONJjGGXkgDb
cRlKVD85bji6MFRgP4+nldOvCFbLkGkPs6huIgzTybHkhJmrNhe77RMHBoaN6bTo
0fv3in+O
-----END PRIVATE KEY-----